### ISSUE TITLE
Weird installation problem about cephes

### ISSUE THREAD

**Issue by zlchilam** [deepmind/torch-cephes#35]
This is the error report below:

Installing https://raw.githubusercontent.com/torch/rocks/master/cephes-0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cephes-0-0.rockspec... switching to 'build' mode
Cloning into 'torch-cephes'...
remote: Counting objects: 197, done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 197 (delta 7), reused 85 (delta 7), pack-reused 0
Receiving objects: 100% (197/197), 370.89 KiB | 120.00 KiB/s, done.
Resolving deltas: 100% (7/7), done.
Checking connectivity... done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/zlchilam/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/zlchilam/torch/install/lib/luarocks/rocks/cephes/0-0";
make
   
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/zlchilam/torch/install
CMake Error at /home/zlchilam/torch/install/share/cmake/torch/TorchPackage.cmake:11 (ADD_LIBRARY):
  add_library cannot create target "cephes" because another target with the
  same name already exists.  The existing target is a module library created
  in source directory "/tmp/luarocks_cephes-0-0-6795/torch-cephes/cephes".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  luasrc/CMakeLists.txt:5 (ADD_TORCH_PACKAGE)

CMake Error at /home/zlchilam/torch/install/share/cmake/torch/TorchPackage.cmake:34 (INSTALL):
  install TARGETS given target "cephes" which does not exist in this
  directory.
Call Stack (most recent call first):
  luasrc/CMakeLists.txt:5 (ADD_TORCH_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cephes-0-0-6795/torch-cephes/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

Error: Build error: Failed building.

It is telling that '' target cephe" is already created "in source directory "/tmp/luarocks_cephes-0-0-6795/torch-cephes/cephes", but actually I could not found anything
about "cephes" in the /tmp. I have reinstalled the torch but also the same problem.

**Comment by iassael** [comment]
Hi zlchilam, I created a pull request [https://github.com/deepmind/torch-cephes/pull/36](https://github.com/deepmind/torch-cephes/pull/36) for your problem, in the meantime it is fixed in this branch [https://github.com/iassael/torch-cephes](https://github.com/iassael/torch-cephes).
