### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by davek44** [deepmind/torch-cephes#37]
I really appreciate the work to wrap these functions. Unless I'm doing something wrong, they don't seem to work with CUDA. I see on the primary site that only double precision is supported, so I'm guessing the single precision representation of floats within CUDA is the problem. Is this correct, and do you have any advice for incorporating these methods into programs that operate primarily on the GPU? Thanks!

**Comment by d11** [comment]
I'm afraid there is no cuda implementation that I know of, and writing one would likely involve some time porting each function individually. There are probably more obstacles than just the float precision. It's not ideal but depending on your application you may be able to get away with doing these computations on the cpu if you are careful about what and when you copy to and from the gpu. I would try this first and see if the performance hit matters in your case, then if it does look at finding or writing cuda versions of the particular functions you need. Cheers!

**Comment by davek44** [comment]
Thanks for the clarification and tips!
